{
 "title": "Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Bucket", "query": "ELMÄTARE" }
  ]
 },
 "panels": [
  {
   "title": "Consumption, hourly",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"now\")\n  |> aggregateWindow(every: 1h, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Consumption, last hour",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: -60m, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"now\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Consumption,  detailed (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"now\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Consumption, Total during time window",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"now\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Line Voltage (V)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"volt\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Line Current (A)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"current\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}